#!/bin/bash
#Beschreibung	: t2
#Autor		: t3
#Version		: t4
#!/bin/bash
#Beschreibung	: t2
#Autor		: t3
#Version		: t4
#!/bin/bash
#Beschreibung	: t2
#Autor		: t3
#Version		: t4
#!/bin/bash
#Beschreibung	: t2
#Autor		: t3
#Version		: t4
